gcp:
  PROJECT_ID: "pesu-mc-485015"
  ZONE: "asia-south1-c"
  INSTANCE_NAME: "pesumc-s2"

crafty:
  SERVER_ID: "ec8f65f2-689d-4806-9f87-658490dceaa9"
  SERVER_IP: "pesu-mc.ddns.net"
  # SERVER_IP: "localhost"

bot:
  ADMIN_ID: "1456845605476368598,1456845605476368598"
